Friend list and online status working (updated)
Segs/Segs pull request #597
Opened 2018-10-01 06:53 UTC by supermandrew

Closes #470 .

Additions/modifications proposed in this pull request:
- Will need to be updated for zoning appropriately.
- 
-

2018-10-01 07:05 UTC, dracc requested changes
Generally, this PR looks good. But there are a few pointed out things I'd like to see done differently and the commit history could use a cleanup.

Good work so far, @supermandrew !

2018-10-01 07:05 UTC, dracc commented on Projects/CoX/Common/NetStructures/Friend.cpp
> +    if(iter!=src_data->m_friends.end())
If you un-reverse this if-statement the code will be shorter, easier to follow and less complex.

2018-10-01 07:05 UTC, dracc commented on Projects/CoX/Servers/GameServer/FriendshipService/FriendHandler.cpp
> -
nit: unnecessary change

2018-10-01 07:42 UTC, dracc commented on Projects/CoX/Common/NetStructures/Friend.cpp
> +    else
The `else` statement can be omitted. 👍

2018-10-02 09:48 UTC, broxen commented on Projects/CoX/Common/NetStructures/Friend.cpp
> +#include "Servers/MapServer/DataHelpers.h"
Doesn't look like you need this, and NetStructures will have a hard time accessing anything from DataHelpers anyway. I'd remove this line.

2018-10-02 09:49 UTC, broxen commented on Projects/CoX/Servers/MapServer/MapInstance.cpp
> -#include "Common/Servers/InternalEvents.h"
Why remove this?

2018-10-02 09:50 UTC, broxen commented on Projects/CoX/Servers/MapServer/MapInstance.cpp
> +void MapInstance::on_update_friendslist(SendFriendListMessage *ev){
please put brackets on their own line per our coding style guide: https://github.com/Segs/Segs/blob/develop/docs/CONTRIBUTING.md#coding-styleguide

2018-10-02 09:50 UTC, broxen commented on Projects/CoX/Servers/MapServer/MapInstance.cpp
> +void MapInstance::on_notify_friend(SendNotifyFriendMessage *ev){
^bracket

2018-10-02 09:53 UTC, broxen requested changes
Some minor notes. Overall great PR!

I'll pull down for testing after these changes have pushed. Thank you Supermandrew!

2018-10-02 15:48 UTC, supermandrew commented on Projects/CoX/Servers/MapServer/MapInstance.cpp
> -#include "Common/Servers/InternalEvents.h"
Because if you look at our current MapInstance, that include is included twice.  Lines 18 and 49.

https://github.com/Segs/Segs/blob/develop/Projects/CoX/Servers/MapServer/MapInstance.cpp

2018-10-02 15:50 UTC, supermandrew commented on Projects/CoX/Servers/MapServer/MapInstance.cpp
> +void MapInstance::on_update_friendslist(SendFriendListMessage *ev){
My mistake!  Got it in FriendHandler, must have missed it here

2018-10-04 05:17 UTC, broxen approved these changes

2018-10-04 07:02 UTC, broxen requested changes
Crashing per my comment above.

2018-10-25 15:05 UTC, broxen commented
Moving to v7

2018-11-28 18:14 UTC, broxen commented
This PR is has gone over 2 months without activity. Is anyone interested in picking this up to finish it off?

2019-01-22 17:15 UTC, broxen commented
After discussing with @crylico he may pick up the reigns here after his TeamHandler is finished.

I'll leave open for now, but will close when crylicos PR comes in.

2020-04-13 06:43 UTC, broxen commented
Closing this out as it's been abandoned for 1.5 years.

2020-04-13 06:43 UTC, closed without merging