#768 Mission Maps
Segs/Segs pull request #769
Opened 2019-02-10 10:39 UTC by Magentah

## Summary
Add functionality to map transfer to mission maps.

### Issues closed
Closes #768 

### Additions/modifications proposed in this pull request:
- Move map data to a file, and potentially update the format to allow for variations (specifically for missions, which have many subsets for maps.
- Update scenegraph to handle parsing of mission file paths when loading mission map scene graphs
- Update MapTemplate to handle mission maps
- Update MapManager to handle mission maps
- Update MapServer to handle mission maps
- Update MapInstance::on_scene_request to handle mission maps.
- Add data for mission maps.
- Update map transfer slash commands and / or mapmenu to handle mission maps (randomise layouts / level ranges  maybe)

2019-02-10 19:15 UTC, broxen reviewed
I know this is WIP, but I left a few comments.

2019-02-10 19:15 UTC, broxen commented on Projects/CoX/Common/Runtime/SceneGraph.cpp
> +    qInfo() << "SceneGraph Path: " << path;
We might want to add these to a logging category, to avoid spamming the main console output

2019-02-10 19:15 UTC, broxen commented on Projects/CoX/Servers/MapServer/MapManager.cpp
> +            qInfo() << "Found Mission Map: " << map_dir_visitor.fileInfo().filePath();
With the addition of these mission maps the output for loading each map file should be categorized. Maybe we provide a generic "Loading maps" type message, and then spit out a warning if one fails to load, otherwise hide each individual map loading message in a category.

2019-02-10 19:15 UTC, broxen commented on Projects/CoX/Servers/MapServer/MapTemplate.cpp
> +            qDebug() << "Is mission map. Mission Level: " << mission_level_cap << " -- Layout: " << mission_layout;
I'd add this debug to a new category as well. Perhaps `logMissions`

2019-02-11 05:00 UTC, Magentah commented
Ya, I was planning on changing all the debug things later. The changes in this so far were just the bare minimum to get it working, and `qInfo()` was quicker, and probably all of it will change before the PR is ready, once I know how I want to structure things.

2019-02-12 17:58 UTC, Magentah commented on Projects/CoX/Common/GameData/map_definitions.cpp
> +        if (abs(char_level - level_range) < abs(char_level - current))
I realize this won’t work correctly and needs to change.

2019-02-12 17:58 UTC, Magentah commented on Projects/CoX/Common/GameData/map_definitions.cpp
> -const MapData &getMapData(const QString &map_name)
I removed a lot of const due to some changes I was making having issues with it, I’ll eventually add all the consts back where able

2019-02-12 17:58 UTC, Magentah commented on Projects/CoX/Common/GameData/map_definitions.h
> +    uint8_t m_layout;       // Sewers_15_Layout_01
I’m thinking that I’ll change this so that there’s only a single mission data for each level, which has all possible layouts in it.

Also need to think about what to do with the mission maps that don’t have levels/latouts..

2019-02-12 17:58 UTC, Magentah commented on Projects/CoX/Servers/MapServer/MapServer.cpp
> +    serializeFromQString(cd, char_data.m_serialized_chardata);
It seems awkward to have to pass character data to the instance (to get their level to give the correct mission map).. I feel like there should be a better option here

2019-02-12 17:58 UTC, Magentah commented on Projects/CoX/Servers/MapServer/MapTemplate.cpp
> +        return QString("maps/missions/%1").arg(map_desc_from_path);
I’m not sure if I like this either, storing mission maps as just their root, and cities as their whole path. Seems awkward

2019-02-12 17:58 UTC, Magentah commented on Projects/CoX/Servers/MapServer/SlashCommand.cpp
> +        map_idx = (map_idx + 1) % 39;   // To prevent crashing if trying to access the map you're on.
Should be a constant at least, or just the total number of maps defined..

2019-02-12 18:29 UTC, broxen commented on Projects/CoX/Servers/MapServer/MapServer.cpp
> +    serializeFromQString(cd, char_data.m_serialized_chardata);
Just pass their level only. In fact, it probably makes more sense to pass the level only, as when sidekicking or in a Team we may want to pass only one player's level for the mission.

2019-02-12 18:30 UTC, broxen commented on Projects/CoX/Common/GameData/map_definitions.h
> +    uint8_t m_layout;       // Sewers_15_Layout_01
I like the idea of keeping that mission data together and calling upon the level/layout as needed. For those without, those values would be zero? Or could be -1?

2019-02-12 18:32 UTC, broxen commented on Projects/CoX/Servers/MapServer/SlashCommand.cpp
> +        map_idx = (map_idx + 1) % 39;   // To prevent crashing if trying to access the map you're on.
Well... this was sort of a hotfix to provide a random zone option. With the changes you're making (and have made to zoning) I'd say we can probably remove the random map change altogether.

Besides, on live, if you "zone" into a map you were already on (`/stuck` for instance) you would simply reload the zone or teleport to the new location. This is the desired behavior here.

2019-02-12 18:33 UTC, broxen commented on Projects/CoX/Servers/MapServer/MapTemplate.cpp
> +        return QString("maps/missions/%1").arg(map_desc_from_path);
Are there instances where maps require their entire name? Or simply sections of it?

We could store the parts in a QStringList and join with `/` when needed?

2019-02-12 18:43 UTC, Magentah commented on Projects/CoX/Servers/MapServer/MapTemplate.cpp
> +        return QString("maps/missions/%1").arg(map_desc_from_path);
Maps only ever use their full name for anything as far as I remember, the shortened name is only used when requesting a new instance of a map

2019-02-23 05:47 UTC, Magentah commented
There's a couple of issues that I've found playing around with this a bit..

1. The COT mission zone seems to load in very briefly, then disappears and becomes entirely black - the same as if the map didn't load.
2. Outdoor_Industrial and Outdoor_Forest both spawn the player out of bounds, and /stuck doesn't help. The other 2 Outdoor zones seem to spawn you kinda correctly, although you're above the floor still.

I haven't implemented 2 of the mission map types yet (unique and Outdoor_Missions) due to their structure being a bit different to everything else, and I want to think about how best to handle them. 

Outdoor_Missions has sub folders for different types of Outdoor mission - Ruined, Forest, etc - then has folders for each layout. Those folders then have several files each, that I'm entirely unsure how to handle at the moment.

e.g.
```
maps/Missions/Outdoor_Missions/Outdoor_City/Outdoor_City_01/Outdoor_City_01a.bin
maps/Missions/Outdoor_Missions/Outdoor_City/Outdoor_City_01/Outdoor_City_01b.bin
maps/Missions/Outdoor_Missions/Outdoor_City/Outdoor_City_01/Outdoor_City_01c.bin

maps/Missions/Outdoor_Missions/Outdoor_Unique/Outdoor_Unique_Forest_01/Outdoor_Unique_Forest_01c.bin
```

Unique missions have a completely different structure all together..

```
maps/Missions/unique/Interdimensional/Interdimensional_01_01.bin
maps/Missions/unique/TrialRooms/Sewers/trial_01_01_room.bin
maps/Missions/unique/TrialRooms/Sewers/trial_01_01_room_spawns.bin
maps/Missions/unique/TrialRooms/Sewers/trial_01_01_room_beacons.bin
maps/Missions/unique/TrialRooms/Sewers/trial_01_01_room_floorbeacons.bin
maps/Missions/unique/jumppuzzles/Jumppuzzles_Layout_01.bin
```

As of right now, you can load in to any of the other mission maps, I just need to work out the best way to handle selecting the layouts as currently it will always select the first layout found.

2019-02-23 06:00 UTC, Magentah commented
Just to give some info about how the mission maps are currently structured --

Each mission map lair type has a single map definition.
```cpp
{55000, "5th_Column", "5th_Column", MapType::MISSION },
```
During startup, the server will go through the maps directory for missions and load all the mission data. For the indoor mission types such as caves, tech, sewers, etc, this means navigating through the folders to the bin files, and building a structure like so:

- Sewer
    - Mission Level Range: 15
        - Mission Layouts:
            - Layout 01
            - Layout 02
                - Sub Layout 01
            - Layout 02
                - Sub Layout 02
    - Mission Level Range: 30
        - Mission Layouts
            - Layout 01
            - Layout 02_01
            - Layout 03_01

For outdoor missions, it's a similar process, however the level range is fixed at 15 (so they're always accessible in the current system).

Then from this structure we dynamically create the file paths when requested, based on the level of the character requesting the map and the layout requested (although the layout selection part isn't implemented yet)

2019-02-23 06:42 UTC, Magentah commented on Projects/CoX/Common/GameData/map_definitions.h
> +    uint8_t m_layout;       // Sewers_15_Layout_01
Those without a level currently use the lowest level "range" value of 15 so that they're always returned. I don't like how this has ended up being structured for outdoor missions though, due to them not really having levels / sublayouts. The unique / outdoor_missions folders will cause more issues probably. I may need to try to think of a new data structure that will be able to handle all the map types without weird uses of some properties (like levels for outdoor missions not existing, but being needed anyway due to how the mission maps work at the moment)

2019-02-23 13:10 UTC, YellowAdder commented
Map names appear at least synonymous with map size which is more informative to present unless we mean to restrict by level, which I don't think we should do. (What makes a map a "level 45 range map"? Just size?) If someone wants to make a low-level mission inside a large map, barring some technical or mechanical reason, why not? 

Ultimately, mission designers should define whether a map is appropriate for their X-level missions. This is how the AE system does it and, if it existed, AE drops any pretense of map's level association. 

(A selected enemy group appears more strongly related to a mission's level range and difficulty than anything with the chosen map. I could be wrong on that, but if I am, I'd very much be interested in how since it has system implications for missions and spawning.) 

In AE, maps are categorized like:

- Map Type
  - Map Length or Category
    - Map

Map Type corresponds to _sets_ such as the City of Villain and Cargo Ship sets. For example:

- Council Set
  - Small | Medium | Large
    - Map 0X to Map XX
- Office Abandoned - City of Heroes Set
  - Tiny | Small | Medium | Large
    - Map 0X to Map XX
- Office Abandoned - City of Villains Set
  - Tiny | Small | Medium | Large
    - Map 0X to Map XX
- Office Transition to Caves Set
  - Tiny | Small | Medium | Large
    - Map 0X to Map XX

Unlike all other types, Unique Maps uses _category_ instead of map length. Atypical maps, such as the outdoor group, are considered categories under this map type. For example:

- Unique Maps
  - Outdoor Maps
    - Atlas Park 01
    - City Map 01 (Industrial)
    - Forest 01
    - Graveyard 01
  - Office
    - Dark Astoria Office
    - Frostfire
    - Etc.

This seems like a pretty good model to mimic, especially since it makes it easy to accommodate future map sets.

2019-02-23 13:28 UTC, Magentah commented
The structure you provided is essentially the same as what I'm currently using, except that I use 15, 30, 45 and 60 instead of tiny, small, medium and large as it made sense at the time to use the sections from the file name. There's no specific reason that it's called "level" other than it's the first name I thought of that'd kinda fit. I can change the name to size and it'd be the same, functionally.

The issue I'm having is how to structure the actual MapData struct, and the sub mission structs, such that it makes sense and fits all map types (cities, indoor missions, outdoor missions, unique missions) without having weird edge cases and if statements for some things when navigating through the folder directory.

Loading maps based on size or level is something that can be changed later once there's ways to actually load them outside of the mapmenu or movezone commands. I don't want to populate the map definitions with each size of each lair just to be able to access them when it shouldn't be that way once the relevant systems are created, so choosing the size based on the characters level was the easiest way to be able test the current system. I may look in to creating a new /missionmap command specifically for navigating through all the mission maps.

2019-02-23 14:34 UTC, YellowAdder commented
> There's no specific reason that it's called "level" other than it's the first name I thought of that'd kinda fit.

That was my instinct too. What changed my mind was seeing the maps with the idea that people were only getting tiny ones up to level 15. They're T.I.N.Y. I was thinking, noooo. This can't be?

>The issue I'm having is how to structure the actual MapData struct, and the sub mission structs, such that it makes sense and fits all map types ...

My first question would be, do we have to handle all types right now? For a first wash, using an approach that doesn't concern itself with edge cases doesn't seem unreasonable. Should we immediately provide for what may be indiscernible map variants, for example? We're going to learn more that may change how we think about their organization and handling as it is. 

For it's part, AE doesn't provide for these possible variants unless they are as you guessed: multiple levels for their base map. That's a good guess, but I'm not convinced yet. I think you're instead right about them being base-map variants. That might be less related to layout alterations as to "map details," offering different sets of spawn and objective markers. You can probably discover whether that's true without too much effort?

>I may look in to creating a new /missionmap command specifically for navigating through all the mission maps.

You're undoubtedly the best judge on how sensible it is compared to cramming it all in the main command. I rather like the idea.

2019-02-23 15:02 UTC, Magentah commented
> > The issue I'm having is how to structure the actual MapData struct, and the sub mission structs, such that it makes sense and fits all map types ...
> 
> My first question would be, do we have to handle all types right now? For a first wash, using an approach that doesn't concern itself with edge cases doesn't seem unreasonable. Should we immediately provide for what may be indiscernible map variants, for example? We're going to learn more that may change how we think about their organization and handling as it is.

I would prefer to make it as reasonable as can be expected right now, rather than just making it work. Just making it work is the easy part, and this would probably be done by now if I were going with that route. But I think that even if we are to change things in the future, having a sensible base to start from makes things easier. 

After thinking things through a bit more I think I may have come up with a somewhat simplistic way to make it work that'll be enough for now, so we'll see..

2019-04-08 19:52 UTC, broxen requested changes
Prior to merge, I'd like to see a lot of the items here addressed. Constness and logging for sure, also some questions about comments and variable names. Overall great PR, just want to tidy it up before it goes in!

Thanks Magenta! I know you're busy right now, so no rush on any of this.

Pushing this out to our next release v0.8

2019-04-08 19:52 UTC, broxen commented on CMakeLists.txt
> +  Mission_5th_Column
These will need to be added to the new map list in Projects\CoX\CMakeList.txt for scripts, otherwise we'll get some errors there.

Or perhaps consolidated there since these folders are only needed for the CoX project.

2019-04-08 19:52 UTC, broxen commented on Projects/CoX/Common/GameData/map_definitions.cpp
> +    qInfo() << "Mission name: " << mission_data.m_mission_name;
All of 17 of these `qInfo()` messages in this PR should be put into a logging category, because we don't really want to spam the server console with this information.

`qInfo()` should really be short informative text that the server is working properly:
`Loading all maps... done!` with more verbose output reserved for categories that can be toggled for troubleshooting, etc.

2019-04-08 19:52 UTC, broxen commented on Projects/CoX/Common/GameData/map_definitions.cpp
> +                            getMissionMapLevelData(map_level, map_data);
Per your discussion with YellowAdder, perhaps we change this to `map_size` or something, as it doesn't have a direct correlation with level (server ops may use any size map for any sort of difficulty or player level)

2019-04-08 19:52 UTC, broxen commented on Projects/CoX/Common/GameData/map_definitions.cpp
> -const MapData &getMapData(const QString &map_name)
I'd like to see the consts replace where possible prior to merging this PR.

2019-04-08 19:52 UTC, broxen commented on Projects/CoX/Common/GameData/map_definitions.cpp
> +    for (auto &map_data : g_defined_map_datas)
here for example, we aren't even changing (nor should we) `g_defined_map_datas`

2019-04-08 19:52 UTC, broxen commented on Projects/CoX/Common/GameData/map_definitions.cpp
> +            return QString("maps/City_Zones/%1/%1.txt").arg(QString(map_data.m_map_name));
What about Trial Zones etc?

2019-04-08 19:52 UTC, broxen commented on Projects/CoX/Common/GameData/map_definitions.h
> +/*
This may be useful to have here, but let's add a blurb at the top to describe what it is we're looking at and why it's relevant.

2019-04-08 19:52 UTC, broxen commented on Projects/CoX/Servers/MapServer/MapTemplate.cpp
> +        // number suffix is likely the level limit (sewers_30 is levels 16-30)
Given your conversation with YellowAdder regarding levels and map sizes, perhaps this comment is dated and could use a rewrite.

2020-09-21 23:46 UTC, nemerle commented
This was merged 'by hand'

2020-09-21 23:46 UTC, closed without merging