Movement
Segs/Segs pull request #891
Opened 2019-05-06 23:10 UTC by spectre1989

## Summary
No-collision movement on the server now matches the client.

### Additions/modifications proposed in this pull request:
The major change that made this work was how the server handles inputs from the client.
- Using the send_id in the input packet, the server is now able to figure out if any of the control state changes in the packet have been seen before.
- Inputs are then queued in the entity input state, and each tick they are processed. The server doesn't need to do any calculations about time, everything it needs is in the control state changes.

### Things I'm Unsure of:
- The way I've translated some of the RE movement code to server-side, it seems to work but I'm not sure how I'd fully test all code paths
- Compiler warnings, which can be ignored and which shouldn't
- When I tested with 2 clients with input and movement logging enabled, the sheer quantity of logs seemed to make my server fall over, if this is unacceptable then perhaps need a way to select which specific entity to log input/movement for?

2019-05-06 23:14 UTC, broxen commented
Regarding `When I tested with 2 clients with input and movement logging enabled, the sheer quantity of logs seemed to make my server fall over, if this is unacceptable then perhaps need a way to select which specific entity to log input/movement for?`

Perhaps a per-character variable `m_log_movement` to check before sending logs out. Not sure that's the cleanest way, but it would work.

2019-05-06 23:22 UTC, spectre1989 commented
> Regarding `When I tested with 2 clients with input and movement logging enabled, the sheer quantity of logs seemed to make my server fall over, if this is unacceptable then perhaps need a way to select which specific entity to log input/movement for?`
> 
> Perhaps a per-character variable `m_log_movement` to check before sending logs out. Not sure that's the cleanest way, but it would work.

And enable it per-character with a /command?

2019-05-06 23:30 UTC, broxen commented
> And enable it per-character with a /command?

Precisely `/logmovement {optional: $target}` or something. Variable may be best in the Entity class, as different types of entities may have movement (Monorail, Blimp, Pedestrians, etc)

2019-05-06 23:53 UTC, broxen commented on Projects/CoX/Common/GameData/StateStorage.h
> +    // whether this state change contains the client pitch/yaw which are sent
These may actually be camera pitch/yaw, and perhaps the angle deviates due to some kind of rounding error with mouse movement? Worth testing to see.

2019-05-06 23:54 UTC, broxen commented on Projects/CoX/Common/GameData/StateStorage.h
> +    float                           m_velocity_scale = 1.0f;
I believe this should increase the speed of all movement if the client has changed it's value.

2019-05-07 00:07 UTC, broxen commented on Projects/CoX/Common/GameData/Movement.cpp
> +static void playerMotionSetInputVelocity(Entity* player, const TickState* tick_state) // based on pmotionSetVel()
The var name `player` is misleading here. A player is always represented by an Entity, but an Entity may or may not be a Player.

2019-05-07 12:32 UTC, spectre1989 commented on Projects/CoX/Common/GameData/Movement.cpp
> +static void playerMotionSetInputVelocity(Entity* player, const TickState* tick_state) // based on pmotionSetVel()
Yeah I'm making an assumption that this code only runs for players, if that's not the case it'll need changing

2019-05-08 14:28 UTC, spectre1989 commented
> > And enable it per-character with a /command?
> 
> Precisely `/logmovement {optional: $target}` or something. Variable may be best in the Entity class, as different types of entities may have movement (Monorail, Blimp, Pedestrians, etc)

ok, I've added it, but can't test it yet because of the db issues we're having at present

2019-05-08 17:22 UTC, broxen commented
Give this is another go pulling the latest from develop head.

2019-05-08 17:22 UTC, broxen commented on Projects/CoX/Servers/MapServer/SlashCommand.cpp
> +    {{"toggleInputLog"}, "Enable input logging for a player", cmdHandler_ToggleInputLog, 9},
Smart idea.

2019-05-08 17:26 UTC, broxen commented on Projects/CoX/Servers/MapServer/SlashCommand.cpp
> +    Entity* target = getTargetEntity(sess);
Following the format of `/teleport` may allow admins to type in a name of a player that they can't target directly (eventually, using UserRouter, another zone etc).

It makes several checks for name and target to avoid duplicate name issues where possible.

```cpp
    QString name = sess.m_ent->name();
    if(!params.isEmpty())
        name = params.join(" ");

    // getTargetByNameOrIdx will always return a valid Entity, or self
    Entity *tgt = getCmdTargetByNameOrIdx(sess, name);
    name = tgt->name(); // make sure we have the final name
```

2019-05-08 22:03 UTC, spectre1989 commented
> Give this is another go pulling the latest from develop head.

Yep that worked, I'll finish up the logging stuff tomorrow

2019-05-10 11:48 UTC, spectre1989 commented on Projects/CoX/Servers/MapServer/SlashCommand.cpp
> +    Entity* target = getTargetEntity(sess);
I've updated it to use that with the latest commit, and tested with 2 clients, switching logging between myself and another player, seems to work.

2019-05-14 10:27 UTC, broxen requested changes
Thank you for working on this spectre!

I'm running into a few issues after building this PR
- server position doesn't actually appear to be updated, I'm not sure if I need to toggle server authority, but `/movement` didn't seem to have any effect.
- using powers sometimes disables movement altogether. In particular "Sprint"
- turning with the mouse or keyboard `q` or `e` has significant latency. It takes the client several seconds to update the current player's rotation.
- Other clients do see player rotation, but with the same delay as seen locally.
- Other clients don't see movement at all.

2019-05-14 10:27 UTC, broxen commented on Projects/CoX/Common/GameData/StateStorage.h
> +      struct
It probably doesn't really matter, but `-wPedantic` is throwing roughly a dozen warnings about Anonymous structs here. Let's name this.

`warning: ISO C++ prohibits anonymous structs [-Wpedantic]`

2019-05-14 10:27 UTC, broxen commented on Projects/CoX/Common/GameData/Movement.cpp
> +static bool floatEquals(float a, float b)
We don't actually use this anywhere. Is there a future use planned, or should we just remove it?

2019-05-14 10:27 UTC, broxen commented on Projects/CoX/Common/GameData/Movement.cpp
> +                            // do a tick!
Errant comment? or TODO?

2019-05-14 10:27 UTC, broxen commented on Projects/CoX/Common/GameData/StateStorage.cpp
> +            {
For code consistency, let's omit brackets on single line code blocks, except for where nested. Referencing our coding guidelines:
```cpp
for (bool key : m_keys)
{
    if (key)
        return true;
}

2019-05-14 10:57 UTC, spectre1989 commented on Projects/CoX/Common/GameData/Movement.cpp
> +                            // do a tick!
It's a comment - control id 8 is "end of tick" which means a tick can be executed. Should I change this comment to something else?

2019-05-14 11:00 UTC, spectre1989 commented on Projects/CoX/Common/GameData/StateStorage.cpp
> +            {
MOTHER OF GOD

2019-05-14 11:04 UTC, spectre1989 commented on Projects/CoX/Common/GameData/Movement.cpp
> +static bool floatEquals(float a, float b)
Oops, just left over from when I was using it, and then I wasn't...

2019-05-14 11:06 UTC, spectre1989 commented on Projects/CoX/Common/GameData/StateStorage.h
> +      struct
Ah yeah, I meant to do that, will do

2019-05-14 12:39 UTC, spectre1989 commented
> Thank you for working on this spectre!
> 
> I'm running into a few issues after building this PR
> 
> * server position doesn't actually appear to be updated, I'm not sure if I need to toggle server authority, but `/movement` didn't seem to have any effect.
> * using powers sometimes disables movement altogether. In particular "Sprint"
> * turning with the mouse or keyboard `q` or `e` has significant latency. It takes the client several seconds to update the current player's rotation.
> * Other clients do see player rotation, but with the same delay as seen locally.
> * Other clients don't see movement at all.

I can't repro those issues locally, are you running the server on your local machine or a remote one? I've only tried running the server on the same machine as the client.

Server authority is likely still broken, I couldn't get it to work before and I've not looked at fixing it yet. I was thinking perhaps (once we're happy with it) we should turn on server authority by default for no-coll movement only, but obviously as all other movement is unimplemented leave it off for that.

2019-05-22 07:57 UTC, spectre1989 commented
I'm still working on an update for this - hope it's alright with you @broxen, I'm integrating stuff from your movement branch as you've got the whole structure and flow of entMotion/entWalk/etc.

2019-05-22 18:29 UTC, broxen commented on Projects/CoX/Common/GameData/Movement.cpp
> +                            // do a tick!
I would make this more verbose so it's clear that the behavior is already there, and this isn't a TODO for future code or something.

2019-05-22 18:30 UTC, broxen commented
Absolutely, feel free to use that code. Tread carefully though, I can't remember what I did there =P

2019-05-28 12:47 UTC, spectre1989 commented
Ok as discussed I've integrated a lot of the code from your movement branch, but I've left out entWorldCollide. For now I'm spoofing player movement so that it roughly matches player movement in the starting area that I was testing with. I've also renamed a lot of the functions to be consistent with yours, I figure that'll make it less confusing to work with going forward if I stop renaming things!

2019-05-28 14:36 UTC, broxen commented
CI is failing due to the use of compare in the body parts changes Nem made recently. I'll try to push a fix for that tonight.

```cpp
/home/travis/build/Segs/Segs/Projects/CoX/Common/GameData/bodypart_definitions.cpp: In member function ‘BodyPart_Data* BodyPartsStorage::getBodyPartFromName(const QByteArray&)’:
/home/travis/build/Segs/Segs/Projects/CoX/Common/GameData/bodypart_definitions.cpp:120:27: error: ‘class QByteArray’ has no member named ‘compare’
         if ( 0==bp.m_Name.compare(name,Qt::CaseInsensitive) )
                           ^~~~~~~
```

2019-05-28 15:16 UTC, nemerle commented
That problem with CI is likely caused by the older Qt version on the server.

2019-05-31 16:27 UTC, cajoebestrotheray commented
> CI is failing due to the use of compare in the body parts changes Nem made recently. I'll try to push a fix for that tonight.
> 
> ```c++
> /home/travis/build/Segs/Segs/Projects/CoX/Common/GameData/bodypart_definitions.cpp: In member function ‘BodyPart_Data* BodyPartsStorage::getBodyPartFromName(const QByteArray&)’:
> /home/travis/build/Segs/Segs/Projects/CoX/Common/GameData/bodypart_definitions.cpp:120:27: error: ‘class QByteArray’ has no member named ‘compare’
>          if ( 0==bp.m_Name.compare(name,Qt::CaseInsensitive) )
>                            ^~~~~~~
> ```

Is there anything I need to do for this? Like merge upstream and push to my branch or something?

2019-05-31 16:31 UTC, broxen commented
We might be able to adjust CI to to use a newer QT version. Also Nem mentioned in discord a possible cmake change that would look for the latest version.

I've been pretty slammed with work and haven't had a chance to look at it, but those are two possible solutions

2019-06-12 06:04 UTC, broxen commented
This is an enormous step in the right direction. Fantastic work spectre!

2019-06-12 06:04 UTC, merged